version: '3'
services:
  postgres:
    image: postgres:latest
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
  server:
    build: ./server
    ports:
      - 9000:9000
    depends_on:
      - postgres
    links:
      - postgres:postgres
