version: '3'
services:
  postgres:
    image: postgres:latest
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=root
    expose:
      - 5432
  server:
    build: ./server
    expose:
      - 9000
    depends_on:
      - postgres
    links:
      - postgres:postgres
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    
    links:
      - server
    depends_on:
      - server
